### ISSUE TITLE
podman API library

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [marhkb/pods#207]
Currently, [vv9k/podman-api-rs](https://github.com/vv9k/podman-api-rs) is being used to interface with podman. This is problematic because it targets podman version 3.4 and is missing features and fixes introduced with newer versions. For example, #127 is being blocked by a spec issue that is fixed in the latest release.

An alternative would be to generate the client code with [openapi-generator](https://github.com/OpenAPITools/openapi-generator). You can grab the latest spec from [here](https://storage.googleapis.com/libpod-master-releases/swagger-latest.yaml) and generate the client code with this command. 

```bash
podman run --rm -v "${PWD}:/local:z" docker.io/openapitools/openapi-generator-cli:latest generate \
    -i /local/spec.yaml \
    -g rust \
    -o /local/gen_out \ 
   --skip-validate-spec
```

I can't really judge the quality of the generated code / how idiomatic it is because I'm still very new to rust.

**Comment by marhkb** [comment]
Many thanks for this tip. Nevertheless, I decide against this approach for the following reasons.

1. the generated code still needs to be adapted to be compiled (replacing `model::Array` with `serde_json::Value::Array`)
2. it is very cumbersome to use the API because no builders are provided (long method signatures)
3. it seems that `system_events_libpod`, `container_logs_libpod` and `containers_stats_all_libpod` do not return streams. This breaks the basic functionality of the application.
4. I think it's too much effort to change the library while we don't know yet what other cans of worms we might open in this process.

In contrast, [podman-api-rs](https://github.com/vv9k/podman-api-rs) is a very convenient crate and I think it would be much less effort to fix the problems there that we have experienced.
I will leave this issue open as I still think the point you raise is valid. So I am willing to change my mind if someone wants to do the hard research to find out if the generated code is better.

**Comment by marhkb** [comment]
Closing this. The cooperation with upstream is very good, and it seems all issues are resolved. Also, at this point, Pods is too tightly coupled with `podman-api-rs`. The effort of changing the backend would be very high. Future Issues should be addressed upstream directly.
