### ISSUE TITLE
refreshing images and containers

### ISSUE THREAD

**Issue by allaeddineomc** [marhkb/pods#306]
the app isn't automatically re scanning for containers and images , if the app is open and an image is pulled from outside the app or a container is created the app won't display the changes until an action is performed inside the app or the app is restarted 
a good solution will be to refresh automatically  every 5 seconds (if that's not expensive in terms of resource usage) or add a refresh button .

**Comment by marhkb** [comment]
Hi @allaeddineomc 

Thanks for your report. It should actually work

[Kooha-2022-09-12-08-33-07.webm](https://user-images.githubusercontent.com/3630213/189588535-b909bf13-52fd-47a9-acf6-b39a8a1e50a7.webm)

Could you describe the exact steps how to reproduce this?

> if the app is open and an image is pulled from outside the app or a container is created the app won't display the changes until an action is performed inside the app

In fact, there is no difference at all whether an image or container was added from the outside or from the inside. For both Pods uses the [events](https://docs.podman.io/en/latest/_static/api.html?version=v4.1#tag/system/operation/SystemEventsLibpod) endpoint to watch for changes.

> automatically every 5 seconds (if that's not expensive in terms of resource usage) or add a refresh button .

Since there is the events endpoint, this is not a good approach. I would rather fix the bugs related to the use of this endpoint.

**Comment by allaeddineomc** [comment]
i wasn't pulling images with podman pull , i was building images with buildah and they didn't appear until the app is restarted , and when they appear after the restart they look grayed out like this 
![image](https://user-images.githubusercontent.com/57415185/189631468-6037a367-d91e-427b-83ee-8283c6244051.png)

**Comment by marhkb** [comment]
Oh, you're correct. Buildah does not give us an event. I checked cockpit-podman and podman-desktop and the images also don't appear there.
I think, I'll try to implement the refresh interval to solve this.

**Comment by marhkb** [comment]
@allaeddineomc 

Could you test?
https://github.com/marhkb/pods/suites/8271877435/artifacts/362121850

**Comment by allaeddineomc** [comment]
works perfectly
