### ISSUE TITLE
 No way to define labels when creating a pod or a container

### ISSUE THREAD

**Issue by vv9k** [marhkb/pods#334]
It would be nice if there was a way to define labels on a container or a pod. I'd imagine a similar widget to the one that is responsible for adding environment variables as they both need to store a key-value pair.

I tried taking an initial stab at it by reworking the `PdsEnvVarRow` to be more generic `PdsKeyValRow` and reusing it for labels, but i think a view has to be unique to each widget, otherwise the values end up in both children that match this class. 

Is creating a separate view and model for labels the way to go or is there something that would allow for a more generic view like `PdsKeyValRow` to be reused for both labels and environment variables?

**Comment by marhkb** [comment]
> I tried taking an initial stab at it by reworking the PdsEnvVarRow to be more generic PdsKeyValRow and reusing it for labels, but i think a view has to be unique to each widget, otherwise the values end up in both children that match this class.
>
> Is creating a separate view and model for labels the way to go or is there something that would allow for a more generic view like PdsKeyValRow to be reused for both labels and environment variables?

Yeah, I think it's for both `PdsEnvVarRow` (view) and `EnvVar` (model) ok to be used in a more generalized way for this purpose. 

So, renaming them, like you did, to `PdsKeyValRow` and to `KeyVal` (model) is all what needs to be done, AFAICS. You also need to rename the ui file `data/resources/ui/env-var/row.ui` and update `data/resources/resources.gresource.xml`.

The renaming part in the container creation page would be quite straightforward because you've already done the same thing in #329

If we want to use other strings than "Key" value "Value" (screenshot) for the container labels, we could also define these two strings as glib properties in the `PdsKeyValRow` to make them customizable.
![grafik](https://user-images.githubusercontent.com/3630213/191976307-bb397fc7-b221-48a2-8b55-ed3fa9a2a580.png)
