### ISSUE TITLE
Ability to edit volumes/port mapping of an existing container

### ISSUE THREAD

**Issue by vhaudiquet** [marhkb/pods#704]
#### Describe your feature request

When creating a container, the GUI allows for choosing filesystems to bind mount in the container, and ports to map between container and host. However, once the container is created, those properties cannot be edited (even though they are available on the container properties json file).

The GUI should allow us to modify such volumes and ports.

(Sorry if it is possible and i couldn't find it)

**Comment by marhkb** [comment]
No, this is currently not possible in the App.
How exactly does your original workflow to change these settings look like?

I couldn't find anything in particular in the API docs (https://docs.podman.io/en/latest/_static/api.html?version=v4.5#tag/containers) how to modify them after creation.

**Comment by vhaudiquet** [comment]
I will try to explain what i want. You tell me if it makes sense.

I'm using containers as build environment, to compile software (currently the old 4.0 kernels). I'm using podman instead of docker, because of how easy it is to use with  your interface, which is really neat.

When i want to compile another kernel elsewhere in my host filesystem, that i have not mapped to the container, i'm stuck.

I think that the container people would rather :
- Extract the image from a running container (https://docs.podman.io/en/latest/_static/api.html?version=v4.5#tag/images/operation/ImageGetLibpod)
- Create a new container, using that images, mapping the wanted volumes/ports
- Run that container

It basically does the same of what i want, which is changing the mapped directory of a container.

However, i could not find a way to export an image from a container in the pods GUI either.

I think adding both options would enhance the features of the app without drawbacks : 
- Adding an option to create an image from a running container, using the export image
- Doing a little bit more work on pods side, having a way to change volume/port mapping after creation (maybe by automatically exporting and re-importing image, effectively re-creating the container), as I think i'm not the only one who could want to do that (but i'm not sure)

Even though the second one might be a bit far-fetched.

**Comment by marhkb** [comment]
Ok, you mean to make some kind of convenience function that changes volumes/port mappings by deleting the old container and adding a new one with the same configuration?

I don't know why you would want the `export` function because you then need to import that image again. But nevertheless, this would be a good feature for Pods.

Have you considered using the `commit` function of the container? I think that should have the same effect as export/import function. You could then use the new image.

![grafik](https://github.com/marhkb/pods/assets/3630213/040e08ca-6c87-49a5-9852-2675048dff38)
